package Reactioncraft.integration;

import Reactioncraft.net.RCN;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;

public class IntegratedItemRegistry {

	public static void loadAll() 
	{
		GameRegistry.registerItem(IntegratedItems.ChainLoop, "RC-Chainloop", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Hammer, "RC-Hammer", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.SandStonePaste, "RC-Sandstonepaste", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.SamonRaw, "RC-rawsamon", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Samon, "RC-samon", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.YellowTailRaw, "RC-yellowtailraw", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.YellowTailCooked, "RC-yellowtailcooked", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Mapinabottle, "RC-Mapinabottle", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Shipinabottle, "RC-Shipinabottle", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Blackdiamondbore, "RC-Blackdiamondbore", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Bloodstonebore, "RC-Bloodstonebore", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.rcendereye, "RC-rcendereye", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.meltedventinite, "RC-meltedventinite", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.meltedwizimite, "RC-meltedwizimite", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstoneHammer, "RC-bloodstoneHammer", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstoneclump, "RC-bloodstoneclump", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.WoodenBookcasedoor, "RC-WoodenBookcasedoor", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.IronBookcasedoor, "RC-IronBookcasedoor", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Metadatacoin, "RC-Metadatacoin", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Crown, "RC-Crown", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.KinglyChest, "RC-KinglyChest", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.KinglyLegs, "RC-KinglyLegs", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.KinglyBoots, "RC-KinglyBoots", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Bag, "RC-Bag", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Sack, "RC-Sack", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Straw, "RC-Straw", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.CoinMould, "RC-CoinMould", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.moltengold, "RC-moltengold", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.moltensilver, "RC-moltensilver", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.moltencopper, "RC-moltencopper", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.moltenbronze, "RC-moltenbronze", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.copperbucket, "RC-copperbucket", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.silverbucket, "RC-silverbucket", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bronzebucket, "RC-bronzebucket", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.goldbucket, "RC-goldbucket", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotRefinedgold, "RC-ingotRefinedgold", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotSilver, "RC-ingotSilver", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotBronze, "RC-ingotBronze", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotCopper, "RC-ingotCopper", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotmould, "RC-ingotmould", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ruby, "RC-ruby", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.emeraldcrown, "RC-emeraldcrown", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.diamondcrown, "RC-diamondcrown", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.rubycrown, "RC-rubycrown", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstonehelm, "RC-bloodstonehelm", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstonechest, "RC-bloodstonechest", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstonelegs, "RC-bloodstonelegs", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstoneboots, "RC-bloodstoneboots", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.GoldChisel, "RC-GoldChisel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.FlintChisel, "RC-FlintChisel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.DiamondChisel, "RC-DiamondChisel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneChisel, "RC-BloodstoneChisel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.CopperChisel, "RC-CopperChisel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.UncutLBGem, "RC-UncutLBGem", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.CutLBGem, "RC-CutLBGem", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.UncutDBGem, "RC-UncutDBGem", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.CutDBGem, "RC-CutDBGem", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.scroll, "RC-scroll", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Knfie, "RC-Knfie", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.EdibleFlesh, "RC-EdibleFlesh", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.cookedCorn, "RC-cookedCorn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.popcornseeds, "RC-popcornseeds", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bagofpopcorn, "RC-bagofpopcorn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.poppedbagofpopcorn, "RC-poppedbagofpopcorn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.UnwrappedCorn, "RC-UnwrappedCorn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.rawcorn, "RC-rawcorn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ChickenNuggets, "RC-ChickenNuggets", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.RawNuggets, "RC-RawNuggets", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.SlicedBread, "RC-SlicedBread", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.HamSandwich, "RC-HamSandwich", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Hamburger, "RC-Hamburger", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Cheeseburger, "RC-Cheeseburger", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Bacon, "RC-Bacon", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BaconRaw, "RC-BaconRaw", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.cheese, "RC-cheese", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.meatcleaver, "RC-meatcleaver", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.churn, "RC-churn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.rawHuman, "RC-rawHuman", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.cookedHuman, "RC-cookedHuman", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.rawLamb, "RC-rawLamb", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.cookedLamb, "RC-cookedLamb", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.rawHorse, "RC-rawHorse", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.cookedHorse, "RC-cookedHorse", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.chickenHead, "RC-chickenHead", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.beefChunk, "RC-beefChunk", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.porkChunk, "RC-porkChunk", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.buns, "RC-buns", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.moltenglass, "RC-moltenglass", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.IceBucket, "RC-IceBucket", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ObsidianBucket, "RC-ObsidianBucket", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bones, "RC-bones", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.scoop, "RC-scoop", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.hiveframe, "RC-hiveframe", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.honeycomb, "RC-honeycomb", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.pollencomb, "RC-pollencomb", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.caught, "RC-caught", "reactioncraft");
		//GameRegistry.registerItem(IntegratedItems.creativeNet, "RC-creativeNet", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.goldrod, "RC-goldrod", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.obsidianingot, "RC-obsidianingot", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotbloodstone, "RC-ingotbloodstone", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ingotsilver, "RC-ingotsilver", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.bloodstonedust, "RC-bloodstonedust", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.blackdiamond, "RC-blackdiamond", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.dragonstoneshard, "RC-dragonstoneshard", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.irondust, "RC-irondust", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.gemdragonstone, "RC-gemdragonstone", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.superheatedironingot, "RC-superheatedironingot", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.goldDust, "RC-goldDust", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.AncientFruit, "RC-AncientFruit", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.AncientFlower, "RC-AncientFlower", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Wrappedcorn, "RC-Wrappedcorn", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.AncientSeeds, "RC-AncientSeeds", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.sugarcaneItem, "RC-sugarcaneItem", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.CornSeed, "RC-CornSeed", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.stalksItem, "RC-stalksItem", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ObbySword, "RC-ObbySword", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ObbyPick, "RC-ObbyPick", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ObbyShovel, "RC-ObbyShovel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ObbyAxe, "RC-ObbyAxe", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.ObbyHoe, "RC-ObbyHoe", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneSword, "RC-BloodstoneSword", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstonePick, "RC-BloodstonePick", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneShovel, "RC-BloodstoneShovel", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneAxe, "RC-BloodstoneAxe", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneHoe, "RC-BloodstoneHoe", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneBlade, "RC-BloodstoneBlade", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.GoldenSwordFragment, "RC-GoldenSwordFragment", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.UnbindedSword, "RC-UnbindedSword", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.BloodstoneDiamondPick, "RC-BloodstoneDiamondPick", "reactioncraft");
		GameRegistry.registerItem(IntegratedItems.Bat, "RC-Bat", "reactioncraft");
	}
	
	public static void loadNet() 
	{
		GameRegistry.registerItem(RCN.hilt, "RC-hilt", "rcn");
		GameRegistry.registerItem(RCN.net, "RC-net", "rcn");
		GameRegistry.registerItem(RCN.completeNet, "RC-completeNet", "rcn");
		GameRegistry.registerItem(RCN.caught, "RC-caught", "rcn");
		GameRegistry.registerItem(RCN.caughtplayer, "RC-caughtplayer", "rcn");
	}
}
